version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
  exclusions:
    paths:
      - pkg/client
