// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OnrampRequestPaymentMethod.
const (
	CARD OnrampRequestPaymentMethod = "CARD"
)

// Valid indicates whether the value is a known member of the OnrampRequestPaymentMethod enum.
func (e OnrampRequestPaymentMethod) Valid() bool {
	switch e {
	case CARD:
		return true
	default:
		return false
	}
}

// Defines values for QuoteRequestOrderSide.
const (
	Buy  QuoteRequestOrderSide = "buy"
	Sell QuoteRequestOrderSide = "sell"
)

// Valid indicates whether the value is a known member of the QuoteRequestOrderSide enum.
func (e QuoteRequestOrderSide) Valid() bool {
	switch e {
	case Buy:
		return true
	case Sell:
		return true
	default:
		return false
	}
}

// Defines values for TradeRequestAuthType.
const (
	TradeRequestAuthTypeApiKey   TradeRequestAuthType = "api_key"
	TradeRequestAuthTypeWebAuthn TradeRequestAuthType = "web_authn"
)

// Valid indicates whether the value is a known member of the TradeRequestAuthType enum.
func (e TradeRequestAuthType) Valid() bool {
	switch e {
	case TradeRequestAuthTypeApiKey:
		return true
	case TradeRequestAuthTypeWebAuthn:
		return true
	default:
		return false
	}
}

// Defines values for TransferExecuteRequestAuthType.
const (
	TransferExecuteRequestAuthTypeApiKey   TransferExecuteRequestAuthType = "api_key"
	TransferExecuteRequestAuthTypeWebAuthn TransferExecuteRequestAuthType = "web_authn"
)

// Valid indicates whether the value is a known member of the TransferExecuteRequestAuthType enum.
func (e TransferExecuteRequestAuthType) Valid() bool {
	switch e {
	case TransferExecuteRequestAuthTypeApiKey:
		return true
	case TransferExecuteRequestAuthTypeWebAuthn:
		return true
	default:
		return false
	}
}

// Defines values for TransferPrepareRequestQtyUnit.
const (
	Base  TransferPrepareRequestQtyUnit = "base"
	Quote TransferPrepareRequestQtyUnit = "quote"
)

// Valid indicates whether the value is a known member of the TransferPrepareRequestQtyUnit enum.
func (e TransferPrepareRequestQtyUnit) Valid() bool {
	switch e {
	case Base:
		return true
	case Quote:
		return true
	default:
		return false
	}
}

// Asset Asset details
type Asset struct {
	Address     *string             `json:"address,omitempty"`
	Chain       *string             `json:"chain,omitempty"`
	Decimals    *int                `json:"decimals,omitempty"`
	Description *string             `json:"description,omitempty"`
	Icon        *string             `json:"icon,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Image       *AssetImage         `json:"image,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	MarketData  *AssetMarketData    `json:"market_data,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Slug        *string             `json:"slug,omitempty"`
	Socials     *AssetSocials       `json:"socials,omitempty"`
	Stable      *bool               `json:"stable,omitempty"`
	Symbol      *string             `json:"symbol,omitempty"`
	Tradeable   *bool               `json:"tradeable,omitempty"`
	Website     *string             `json:"website,omitempty"`
}

// AssetImage defines model for AssetImage.
type AssetImage struct {
	Large *string `json:"large,omitempty"`
	Small *string `json:"small,omitempty"`
	Thumb *string `json:"thumb,omitempty"`
}

// AssetMarketData defines model for AssetMarketData.
type AssetMarketData struct {
	CirculatingSupply *int64 `json:"circulating_supply,omitempty"`
	MaxSupply         *int64 `json:"max_supply,omitempty"`
	TotalSupply       *int64 `json:"total_supply,omitempty"`
}

// AssetSocials defines model for AssetSocials.
type AssetSocials struct {
	FacebookUsername *string `json:"facebook_username,omitempty"`
	OfficialForumUrl *string `json:"official_forum_url,omitempty"`
	SubredditUrl     *string `json:"subreddit_url,omitempty"`
	XUsername        *string `json:"x_username,omitempty"`
}

// Balance defines model for Balance.
type Balance struct {
	Asset     *string             `json:"asset,omitempty"`
	Balance   *string             `json:"balance,omitempty"`
	Chain     *string             `json:"chain,omitempty"`
	Decimals  *int                `json:"decimals,omitempty"`
	Icon      *string             `json:"icon,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Stable    *bool               `json:"stable,omitempty"`
	Symbol    *string             `json:"symbol,omitempty"`
	Tradeable *bool               `json:"tradeable,omitempty"`
}

// BalanceResponse defines model for BalanceResponse.
type BalanceResponse struct {
	Balances *[]Balance `json:"balances,omitempty"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	ApiKey struct {
		PublicKey string `json:"public_key"`
	} `json:"api_key"`
}

// CreatedWallet defines model for CreatedWallet.
type CreatedWallet struct {
	Address         *string `json:"address,omitempty"`
	AddressType     *string `json:"address_type,omitempty"`
	WalletAccountId *string `json:"wallet_account_id,omitempty"`
	WalletId        *string `json:"wallet_id,omitempty"`
}

// OnrampRequest defines model for OnrampRequest.
type OnrampRequest struct {
	// Amount Fiat amount in USD to onramp
	Amount string `json:"amount"`

	// Chain Blockchain chain (e.g. solana)
	Chain string `json:"chain"`

	// PaymentMethod Payment method for the onramp
	PaymentMethod OnrampRequestPaymentMethod `json:"payment_method"`
}

// OnrampRequestPaymentMethod Payment method for the onramp
type OnrampRequestPaymentMethod string

// OnrampResponse defines model for OnrampResponse.
type OnrampResponse struct {
	// Url Time-limited onramp URL with embedded session token
	Url *string `json:"url,omitempty"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	Email   *openapi_types.Email `json:"email,omitempty"`
	Id      *string              `json:"id,omitempty"`
	Wallets *[]Wallet            `json:"wallets,omitempty"`
}

// QuoteIssue defines model for QuoteIssue.
type QuoteIssue struct {
	Balance *QuoteIssueBalance `json:"balance,omitempty"`
	Message string             `json:"message"`
}

// QuoteIssueBalance defines model for QuoteIssueBalance.
type QuoteIssueBalance struct {
	Actual   string `json:"actual"`
	Expected string `json:"expected"`
}

// QuoteRequest defines model for QuoteRequest.
type QuoteRequest struct {
	BaseAsset  string                `json:"base_asset"`
	Chain      string                `json:"chain"`
	OrderSide  QuoteRequestOrderSide `json:"order_side"`
	Qty        string                `json:"qty"`
	QuoteAsset string                `json:"quote_asset"`
}

// QuoteRequestOrderSide defines model for QuoteRequest.OrderSide.
type QuoteRequestOrderSide string

// QuoteResponse defines model for QuoteResponse.
type QuoteResponse struct {
	BaseAsset  string            `json:"base_asset"`
	Fee        string            `json:"fee"`
	FeeAsset   string            `json:"fee_asset"`
	Issues     []QuoteIssue      `json:"issues"`
	OrderSide  string            `json:"order_side"`
	Payloads   []UnsignedPayload `json:"payloads"`
	Qty        string            `json:"qty"`
	QtyOut     string            `json:"qty_out"`
	QuoteAsset string            `json:"quote_asset"`
	QuoteId    string            `json:"quote_id"`
}

// TradeRequest Trade execution request. Signatures are matched to cached server-side payloads.
type TradeRequest struct {
	// AuthType The authentication type used for signing
	AuthType TradeRequestAuthType `json:"auth_type"`

	// QuoteId The quote ID returned from the quote endpoint
	QuoteId string `json:"quote_id"`

	// Signatures Signatures for the payloads returned from the quote endpoint (in order)
	Signatures []string `json:"signatures"`
}

// TradeRequestAuthType The authentication type used for signing
type TradeRequestAuthType string

// TradeResponse Synchronous trade response with order ID and transaction hash
type TradeResponse struct {
	// OrderId The created order ID
	OrderId *openapi_types.UUID `json:"order_id,omitempty"`

	// TxHash The blockchain transaction hash
	TxHash *string `json:"tx_hash,omitempty"`
}

// TransferExecuteRequest defines model for TransferExecuteRequest.
type TransferExecuteRequest struct {
	// AuthType The authentication type used for signing
	AuthType   TransferExecuteRequestAuthType `json:"auth_type"`
	Signatures []string                       `json:"signatures"`
	TransferId openapi_types.UUID             `json:"transfer_id"`
}

// TransferExecuteRequestAuthType The authentication type used for signing
type TransferExecuteRequestAuthType string

// TransferExecuteResponse defines model for TransferExecuteResponse.
type TransferExecuteResponse struct {
	Asset    *string `json:"asset,omitempty"`
	Chain    *string `json:"chain,omitempty"`
	Fee      *string `json:"fee,omitempty"`
	From     *string `json:"from,omitempty"`
	Received *string `json:"received,omitempty"`
	Sent     *string `json:"sent,omitempty"`
	To       *string `json:"to,omitempty"`
	TxHash   *string `json:"tx_hash,omitempty"`
}

// TransferPrepareRequest defines model for TransferPrepareRequest.
type TransferPrepareRequest struct {
	// Asset Asset contract address
	Asset string `json:"asset"`

	// Chain Blockchain chain (e.g., solana, base)
	Chain string `json:"chain"`

	// Qty Transfer quantity
	Qty string `json:"qty"`

	// QtyUnit Unit of quantity (base for token amount, quote for USD)
	QtyUnit TransferPrepareRequestQtyUnit `json:"qty_unit"`

	// To Recipient address
	To string `json:"to"`
}

// TransferPrepareRequestQtyUnit Unit of quantity (base for token amount, quote for USD)
type TransferPrepareRequestQtyUnit string

// TransferPrepareResponse defines model for TransferPrepareResponse.
type TransferPrepareResponse struct {
	Payloads   *[]UnsignedPayload  `json:"payloads,omitempty"`
	TransferId *openapi_types.UUID `json:"transfer_id,omitempty"`
}

// UnsignedPayload defines model for UnsignedPayload.
type UnsignedPayload struct {
	Digest  string `json:"digest"`
	Payload string `json:"payload"`
}

// Wallet defines model for Wallet.
type Wallet struct {
	Address *string `json:"address,omitempty"`
	Chain   *string `json:"chain,omitempty"`
}

// WalletCreationResult defines model for WalletCreationResult.
type WalletCreationResult struct {
	Wallets *[]CreatedWallet `json:"wallets,omitempty"`
}

// Version defines model for version.
type Version = string

// GetAssetsParams defines parameters for GetAssets.
type GetAssetsParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`

	// Evm Include EVM chain assets
	Evm *bool `form:"evm,omitempty" json:"evm,omitempty"`
}

// GetBalancesParams defines parameters for GetBalances.
type GetBalancesParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`

	// Evm Include EVM chain balances
	Evm *bool `form:"evm,omitempty" json:"evm,omitempty"`
}

// CreateWalletParams defines parameters for CreateWallet.
type CreateWalletParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// CreateOnrampParams defines parameters for CreateOnramp.
type CreateOnrampParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// GetProfileParams defines parameters for GetProfile.
type GetProfileParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// CreateQuoteParams defines parameters for CreateQuote.
type CreateQuoteParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// ExecuteTradeParams defines parameters for ExecuteTrade.
type ExecuteTradeParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// ExecuteTransferParams defines parameters for ExecuteTransfer.
type ExecuteTransferParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// PrepareTransferParams defines parameters for PrepareTransfer.
type PrepareTransferParams struct {
	// Version API version date (YYYY-MM-DD)
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest

// CreateOnrampJSONRequestBody defines body for CreateOnramp for application/json ContentType.
type CreateOnrampJSONRequestBody = OnrampRequest

// CreateQuoteJSONRequestBody defines body for CreateQuote for application/json ContentType.
type CreateQuoteJSONRequestBody = QuoteRequest

// ExecuteTradeJSONRequestBody defines body for ExecuteTrade for application/json ContentType.
type ExecuteTradeJSONRequestBody = TradeRequest

// ExecuteTransferJSONRequestBody defines body for ExecuteTransfer for application/json ContentType.
type ExecuteTransferJSONRequestBody = TransferExecuteRequest

// PrepareTransferJSONRequestBody defines body for PrepareTransfer for application/json ContentType.
type PrepareTransferJSONRequestBody = TransferPrepareRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAssets request
	GetAssets(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBalances request
	GetBalances(ctx context.Context, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateWalletWithBody request with any body
	CreateWalletWithBody(ctx context.Context, params *CreateWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateWallet(ctx context.Context, params *CreateWalletParams, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOnrampWithBody request with any body
	CreateOnrampWithBody(ctx context.Context, params *CreateOnrampParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOnramp(ctx context.Context, params *CreateOnrampParams, body CreateOnrampJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProfile request
	GetProfile(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateQuoteWithBody request with any body
	CreateQuoteWithBody(ctx context.Context, params *CreateQuoteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateQuote(ctx context.Context, params *CreateQuoteParams, body CreateQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExecuteTradeWithBody request with any body
	ExecuteTradeWithBody(ctx context.Context, params *ExecuteTradeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecuteTrade(ctx context.Context, params *ExecuteTradeParams, body ExecuteTradeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExecuteTransferWithBody request with any body
	ExecuteTransferWithBody(ctx context.Context, params *ExecuteTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecuteTransfer(ctx context.Context, params *ExecuteTransferParams, body ExecuteTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PrepareTransferWithBody request with any body
	PrepareTransferWithBody(ctx context.Context, params *PrepareTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PrepareTransfer(ctx context.Context, params *PrepareTransferParams, body PrepareTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAssets(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAssetsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBalances(ctx context.Context, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBalancesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateWalletWithBody(ctx context.Context, params *CreateWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateWalletRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateWallet(ctx context.Context, params *CreateWalletParams, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateWalletRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOnrampWithBody(ctx context.Context, params *CreateOnrampParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOnrampRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOnramp(ctx context.Context, params *CreateOnrampParams, body CreateOnrampJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOnrampRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProfile(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProfileRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateQuoteWithBody(ctx context.Context, params *CreateQuoteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateQuoteRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateQuote(ctx context.Context, params *CreateQuoteParams, body CreateQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateQuoteRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteTradeWithBody(ctx context.Context, params *ExecuteTradeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteTradeRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteTrade(ctx context.Context, params *ExecuteTradeParams, body ExecuteTradeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteTradeRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteTransferWithBody(ctx context.Context, params *ExecuteTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteTransferRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteTransfer(ctx context.Context, params *ExecuteTransferParams, body ExecuteTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteTransferRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PrepareTransferWithBody(ctx context.Context, params *PrepareTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPrepareTransferRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PrepareTransfer(ctx context.Context, params *PrepareTransferParams, body PrepareTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPrepareTransferRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAssetsRequest generates requests for GetAssets
func NewGetAssetsRequest(server string, params *GetAssetsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/assets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Evm != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "evm", *params.Evm, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBalancesRequest generates requests for GetBalances
func NewGetBalancesRequest(server string, params *GetBalancesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/balances")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Evm != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "evm", *params.Evm, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateWalletRequest calls the generic CreateWallet builder with application/json body
func NewCreateWalletRequest(server string, params *CreateWalletParams, body CreateWalletJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateWalletRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateWalletRequestWithBody generates requests for CreateWallet with any type of body
func NewCreateWalletRequestWithBody(server string, params *CreateWalletParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/create-wallet")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateOnrampRequest calls the generic CreateOnramp builder with application/json body
func NewCreateOnrampRequest(server string, params *CreateOnrampParams, body CreateOnrampJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOnrampRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateOnrampRequestWithBody generates requests for CreateOnramp with any type of body
func NewCreateOnrampRequestWithBody(server string, params *CreateOnrampParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/onramp")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProfileRequest generates requests for GetProfile
func NewGetProfileRequest(server string, params *GetProfileParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/profile/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateQuoteRequest calls the generic CreateQuote builder with application/json body
func NewCreateQuoteRequest(server string, params *CreateQuoteParams, body CreateQuoteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateQuoteRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateQuoteRequestWithBody generates requests for CreateQuote with any type of body
func NewCreateQuoteRequestWithBody(server string, params *CreateQuoteParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/quote")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewExecuteTradeRequest calls the generic ExecuteTrade builder with application/json body
func NewExecuteTradeRequest(server string, params *ExecuteTradeParams, body ExecuteTradeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecuteTradeRequestWithBody(server, params, "application/json", bodyReader)
}

// NewExecuteTradeRequestWithBody generates requests for ExecuteTrade with any type of body
func NewExecuteTradeRequestWithBody(server string, params *ExecuteTradeParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/trade")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewExecuteTransferRequest calls the generic ExecuteTransfer builder with application/json body
func NewExecuteTransferRequest(server string, params *ExecuteTransferParams, body ExecuteTransferJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecuteTransferRequestWithBody(server, params, "application/json", bodyReader)
}

// NewExecuteTransferRequestWithBody generates requests for ExecuteTransfer with any type of body
func NewExecuteTransferRequestWithBody(server string, params *ExecuteTransferParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/transfer/execute")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPrepareTransferRequest calls the generic PrepareTransfer builder with application/json body
func NewPrepareTransferRequest(server string, params *PrepareTransferParams, body PrepareTransferJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPrepareTransferRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPrepareTransferRequestWithBody generates requests for PrepareTransfer with any type of body
func NewPrepareTransferRequestWithBody(server string, params *PrepareTransferParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/defi/core/transfer/prepare")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAssetsWithResponse request
	GetAssetsWithResponse(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*GetAssetsResponse, error)

	// GetBalancesWithResponse request
	GetBalancesWithResponse(ctx context.Context, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*GetBalancesResponse, error)

	// CreateWalletWithBodyWithResponse request with any body
	CreateWalletWithBodyWithResponse(ctx context.Context, params *CreateWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateWalletResponse, error)

	CreateWalletWithResponse(ctx context.Context, params *CreateWalletParams, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateWalletResponse, error)

	// CreateOnrampWithBodyWithResponse request with any body
	CreateOnrampWithBodyWithResponse(ctx context.Context, params *CreateOnrampParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOnrampResponse, error)

	CreateOnrampWithResponse(ctx context.Context, params *CreateOnrampParams, body CreateOnrampJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOnrampResponse, error)

	// GetProfileWithResponse request
	GetProfileWithResponse(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*GetProfileResponse, error)

	// CreateQuoteWithBodyWithResponse request with any body
	CreateQuoteWithBodyWithResponse(ctx context.Context, params *CreateQuoteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateQuoteResponse, error)

	CreateQuoteWithResponse(ctx context.Context, params *CreateQuoteParams, body CreateQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateQuoteResponse, error)

	// ExecuteTradeWithBodyWithResponse request with any body
	ExecuteTradeWithBodyWithResponse(ctx context.Context, params *ExecuteTradeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteTradeResponse, error)

	ExecuteTradeWithResponse(ctx context.Context, params *ExecuteTradeParams, body ExecuteTradeJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteTradeResponse, error)

	// ExecuteTransferWithBodyWithResponse request with any body
	ExecuteTransferWithBodyWithResponse(ctx context.Context, params *ExecuteTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteTransferResponse, error)

	ExecuteTransferWithResponse(ctx context.Context, params *ExecuteTransferParams, body ExecuteTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteTransferResponse, error)

	// PrepareTransferWithBodyWithResponse request with any body
	PrepareTransferWithBodyWithResponse(ctx context.Context, params *PrepareTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PrepareTransferResponse, error)

	PrepareTransferWithResponse(ctx context.Context, params *PrepareTransferParams, body PrepareTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*PrepareTransferResponse, error)
}

type GetAssetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Asset
	JSON500      *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAssetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAssetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBalancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BalanceResponse
	JSON401      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetBalancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBalancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateWalletResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *WalletCreationResult
	JSON400      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateWalletResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateWalletResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateOnrampResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OnrampResponse
	JSON400      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON422 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateOnrampResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOnrampResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProfileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProfileResponse
	JSON400      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetProfileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProfileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateQuoteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QuoteResponse
	JSON400      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON422 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateQuoteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateQuoteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExecuteTradeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TradeResponse
	JSON400      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON422 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ExecuteTradeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecuteTradeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExecuteTransferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransferExecuteResponse
	JSON400      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON404 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON422 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ExecuteTransferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecuteTransferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PrepareTransferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransferPrepareResponse
	JSON400      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON422 *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON500 *struct {
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PrepareTransferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PrepareTransferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAssetsWithResponse request returning *GetAssetsResponse
func (c *ClientWithResponses) GetAssetsWithResponse(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*GetAssetsResponse, error) {
	rsp, err := c.GetAssets(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAssetsResponse(rsp)
}

// GetBalancesWithResponse request returning *GetBalancesResponse
func (c *ClientWithResponses) GetBalancesWithResponse(ctx context.Context, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*GetBalancesResponse, error) {
	rsp, err := c.GetBalances(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBalancesResponse(rsp)
}

// CreateWalletWithBodyWithResponse request with arbitrary body returning *CreateWalletResponse
func (c *ClientWithResponses) CreateWalletWithBodyWithResponse(ctx context.Context, params *CreateWalletParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateWalletResponse, error) {
	rsp, err := c.CreateWalletWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateWalletResponse(rsp)
}

func (c *ClientWithResponses) CreateWalletWithResponse(ctx context.Context, params *CreateWalletParams, body CreateWalletJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateWalletResponse, error) {
	rsp, err := c.CreateWallet(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateWalletResponse(rsp)
}

// CreateOnrampWithBodyWithResponse request with arbitrary body returning *CreateOnrampResponse
func (c *ClientWithResponses) CreateOnrampWithBodyWithResponse(ctx context.Context, params *CreateOnrampParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOnrampResponse, error) {
	rsp, err := c.CreateOnrampWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOnrampResponse(rsp)
}

func (c *ClientWithResponses) CreateOnrampWithResponse(ctx context.Context, params *CreateOnrampParams, body CreateOnrampJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOnrampResponse, error) {
	rsp, err := c.CreateOnramp(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOnrampResponse(rsp)
}

// GetProfileWithResponse request returning *GetProfileResponse
func (c *ClientWithResponses) GetProfileWithResponse(ctx context.Context, params *GetProfileParams, reqEditors ...RequestEditorFn) (*GetProfileResponse, error) {
	rsp, err := c.GetProfile(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProfileResponse(rsp)
}

// CreateQuoteWithBodyWithResponse request with arbitrary body returning *CreateQuoteResponse
func (c *ClientWithResponses) CreateQuoteWithBodyWithResponse(ctx context.Context, params *CreateQuoteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateQuoteResponse, error) {
	rsp, err := c.CreateQuoteWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateQuoteResponse(rsp)
}

func (c *ClientWithResponses) CreateQuoteWithResponse(ctx context.Context, params *CreateQuoteParams, body CreateQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateQuoteResponse, error) {
	rsp, err := c.CreateQuote(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateQuoteResponse(rsp)
}

// ExecuteTradeWithBodyWithResponse request with arbitrary body returning *ExecuteTradeResponse
func (c *ClientWithResponses) ExecuteTradeWithBodyWithResponse(ctx context.Context, params *ExecuteTradeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteTradeResponse, error) {
	rsp, err := c.ExecuteTradeWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteTradeResponse(rsp)
}

func (c *ClientWithResponses) ExecuteTradeWithResponse(ctx context.Context, params *ExecuteTradeParams, body ExecuteTradeJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteTradeResponse, error) {
	rsp, err := c.ExecuteTrade(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteTradeResponse(rsp)
}

// ExecuteTransferWithBodyWithResponse request with arbitrary body returning *ExecuteTransferResponse
func (c *ClientWithResponses) ExecuteTransferWithBodyWithResponse(ctx context.Context, params *ExecuteTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteTransferResponse, error) {
	rsp, err := c.ExecuteTransferWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteTransferResponse(rsp)
}

func (c *ClientWithResponses) ExecuteTransferWithResponse(ctx context.Context, params *ExecuteTransferParams, body ExecuteTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteTransferResponse, error) {
	rsp, err := c.ExecuteTransfer(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteTransferResponse(rsp)
}

// PrepareTransferWithBodyWithResponse request with arbitrary body returning *PrepareTransferResponse
func (c *ClientWithResponses) PrepareTransferWithBodyWithResponse(ctx context.Context, params *PrepareTransferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PrepareTransferResponse, error) {
	rsp, err := c.PrepareTransferWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePrepareTransferResponse(rsp)
}

func (c *ClientWithResponses) PrepareTransferWithResponse(ctx context.Context, params *PrepareTransferParams, body PrepareTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*PrepareTransferResponse, error) {
	rsp, err := c.PrepareTransfer(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePrepareTransferResponse(rsp)
}

// ParseGetAssetsResponse parses an HTTP response from a GetAssetsWithResponse call
func ParseGetAssetsResponse(rsp *http.Response) (*GetAssetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAssetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Asset
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetBalancesResponse parses an HTTP response from a GetBalancesWithResponse call
func ParseGetBalancesResponse(rsp *http.Response) (*GetBalancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBalancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BalanceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateWalletResponse parses an HTTP response from a CreateWalletWithResponse call
func ParseCreateWalletResponse(rsp *http.Response) (*CreateWalletResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateWalletResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest WalletCreationResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateOnrampResponse parses an HTTP response from a CreateOnrampWithResponse call
func ParseCreateOnrampResponse(rsp *http.Response) (*CreateOnrampResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOnrampResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OnrampResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetProfileResponse parses an HTTP response from a GetProfileWithResponse call
func ParseGetProfileResponse(rsp *http.Response) (*GetProfileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProfileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProfileResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateQuoteResponse parses an HTTP response from a CreateQuoteWithResponse call
func ParseCreateQuoteResponse(rsp *http.Response) (*CreateQuoteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateQuoteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseExecuteTradeResponse parses an HTTP response from a ExecuteTradeWithResponse call
func ParseExecuteTradeResponse(rsp *http.Response) (*ExecuteTradeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecuteTradeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TradeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseExecuteTransferResponse parses an HTTP response from a ExecuteTransferWithResponse call
func ParseExecuteTransferResponse(rsp *http.Response) (*ExecuteTransferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecuteTransferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransferExecuteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePrepareTransferResponse parses an HTTP response from a PrepareTransferWithResponse call
func ParsePrepareTransferResponse(rsp *http.Response) (*PrepareTransferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PrepareTransferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransferPrepareResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
